apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: guard
    component: message
  ports:
    - port: {{ .Values.service.messagePort }}
      targetPort: 8080
