apiVersion: v1
entries:
  cluster-heist:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-05-22T13:18:03.402072454Z"
    description: 'Cluster Heist: The Helm Job — intentionally misconfigured target
      application for educational Kubernetes gameplay.'
    digest: a795ec69d586f12f27081e1afe5a3fe0cc04009aa7efbcd60ecf4e1124c86411
    keywords:
    - education
    - kubernetes
    - helm
    - game
    maintainers:
    - name: ClusterBank Security Division
    name: cluster-heist
    type: application
    urls:
    - cluster-heist-1.0.0.tgz
    version: 1.0.0
generated: "2026-05-22T13:18:03.398686779Z"
